GET https://localhost:8080/profile/me
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1ZXIzQGdtYWlsLmNvbSIsInJvbGVzIjpbXSwiaWF0IjoxNzQxNTE2MDc0LCJleHAiOjE3NDE2MDI0NzR9.x_LkghCSSjW0fZ4gsIk9iN1RJHlYOAl5mvS8lkBR8MKWPOlWR8hoobuG0kPo_IeUvDyZycSNw6xkncudfBTW4Q